### ISSUE TITLE
init.vim에 질문있습니다

### ISSUE THREAD

**Issue by sunghyouk** [johngrib/dotfiles#4]
```vim
for include_file in uniq(sort(globpath(&rtp, 'vim-include/*.vim', 0, 1)))
    execute "source " . include_file
endfor
```

안녕하세요, `vimwiki`를 검색하다 설명이 너무 잘 되어 있어서 오늘부터 쓰기 시작한 초보 vimer입니다.
다름 아니라 dotfiles/init.vim에서 위와 같은 for문을 쓰셨는데,

이게 vim-include 디렉토리에 있는 각 plugin의 설정 .vim 파일을 읽어 들여서 vi로 보내는 반복문인가요?

제 init.vim이 너무 길어져서 lua로 보낼 것은 보내고 아니면 저 반복문 써서 좀 짧게 줄여볼까 합니다.

알려 주시면 감사하겠습니다.

감사합니다.

**Comment by johngrib** [comment]
네 맞습니다. 일일이 지정하기 귀찮아서 저 경로에 있는 파일 다 읽게 설정한 거에요.
